# Generated by Django 3.2 on 2024-04-16 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('whisky_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='SendTime',
            field=models.DateTimeField(db_column='SendTime', default=django.utils.timezone.now),
        ),
    ]
