# Generated by Django 3.2 on 2024-04-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisky_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='IsDeleted',
            field=models.BooleanField(db_column='IsDeleted', default=False),
        ),
    ]
