# Generated by Django 3.2 on 2024-04-08 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whisky_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
