# Generated by Django 3.2 on 2024-04-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisky_app', '0002_alter_message_sendtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='IsSensitive',
            field=models.BooleanField(db_column='IsSensitive', default=False),
        ),
    ]
