# Generated by Django 3.2 on 2024-04-16 02:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('whisky_app', '0002_alter_review_isdeleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='CommentTime',
            field=models.DateTimeField(db_column='CommentTime', default=django.utils.timezone.now),
        ),
    ]
